This is a General tutorial for pytorch environment

In [1]:
#Import pyTorch
import torch as t
#import numpy
import numpy as np
#import sklearn data sets
from sklearn import datasets
print("Done!")
#setting up cuda:
# on any tensor or model use.cuda()

Done!


In [2]:
#setting default tensor format to be cuda
t.set_default_tensor_type('torch.cuda.FloatTensor')
#alternatively you can use this:
#dtype = torch.cuda.FloatTensor
#w1 = t.method(args).type(dtype)
x = t.Tensor(5)
x.data.zero_()
print(x.size())
print(x)
y = t.Tensor(4,5).cuda()
y.data.zero_()
print(y)
print(y.size())
test_np_array = np.zeros((10,10))
test_torch_tensor = t.Tensor(1000,1000).cuda()
test_torch_tensor.data.zero_()
print(test_torch_tensor.shape)
print(test_torch_tensor)
# get type
print("Done!")

torch.Size([5])
tensor([0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([4, 5])
torch.Size([1000, 1000])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
Done!


In [ ]:
# define AI functions:
# load data
# change format of the data
# torch.softmax()
# torch.einsum()**
#
print("Done!")

In [ ]:
# iterate x epochs
#  run the model
#  compute loss
#  compute BP
#  compute gradient
#  perform gradient decent
#step size is a
a = 0.03
x = input_var
y = true_label
W.requires_grad = True
b.requires_grad = True
for i in range(2000):
    y_hat = softmax(matmul(W,x)+b)
    loss = cross_entropy(y, y_hat)
    loss.backward()
    W.data -= a * W.grad
    b.data -= a * b.grad
    W.grad.data.zero_()
    b.grad.data.zero_()
print("Done!")

In [ ]:
#pytorch optimization librariy
a = 0.03
parameters = [W1, b1, W2, b2]
optimizer = torch.optim.SGD(parameters, lr = a)
#changes will be:
for i in range(3000):
    h = torch.sigmoid(mutual(W1, x) + b1)
    y_hat = softmax(matmul(W2,h)+b2)
    loss = cross_entropy()
    optimizer.step()
    optimizer.zero_grad()